### PR TITLE
Fixed naming conventions for raw/web sockets

### PR DESCRIPTION
**Pull request by davidchappelle**

### CODE REVIEW

**Comment by jpetso** [comment]
Why?

**Comment by davidchappelle** [comment]
For consistency. I now have to add a named pipe server and having named_pipe and rawsocket just doesn't look right.

**Comment by jpetso** [comment]
Well, the spec calls it [RawSocket](https://github.com/tavendo/WAMP/blob/master/spec/advanced/rawsocket-transport.md) and [WebSocket](https://en.wikipedia.org/wiki/WebSocket) also doesn't have spaces, so to me it looks less correct if you add an underscore (replacement for a space) to the name. Especially in the user-facing command-line options.

I would say "named pipe" and "WebSocket" (or websocket if I'm lazy about camel-casing) in regular writing, consequently I disagree that it looks wrong in code.

**Comment by davidchappelle** [comment]
Fair enough. I don't care enough to argue. It just looked more correct IMHO
as here is no such thing as a rawsocket, or a websocket for that matter.
These are just common misspellings.

**Pull request closed without merging**
